server:
  port: ${PORT:9191}

spring:
  application:
    name: API-GATEWAY
  config:
    import: "optional:configserver:"
  cloud:
    gateway:
      routes:
        - id: ORDERS-SERVICE
          uri: lb://ORDERS-SERVICE
          predicates:
            - Path=/orders/**
        - id: SHIPPING-SERVICE
          uri: lb://SHIPPING-SERVICE
          predicates:
            - Path=/shipping/**
logging:
  level:
    org.springframework.cloud.gateway: TRACE

eureka:
  instance:
    homePageUrl: https://${eureka.instance.hostName}/
    home-page-url-path: https://${eureka.instance.hostName}
  client:
    serviceUrl:
      defaultZone: http://servicediscorvery.herokuapp.com/eureka
      non-secure-port: 80
      secure-port: 443